#!/bin/bash

# alacarte is main menu editor

sudo yum install vim autoconf automake gcc gcc-c++ libtool subversion git wget lsb man-pages zlib-devel cmake alacarte gettext-devel gettext libsysfs-devel libcap-devel

