syntax on
set nobackup
set expandtab
set ai
set shiftwidth=4
set tabstop=4
" set cursorline
set hlsearch
set incsearch
set showmode
set ruler
set showmatch
" highlight right margin
" set colorcolumn=80    
colorscheme desert
autocmd FileType make setlocal noexpandtab
autocmd FileType automake setlocal noexpandtab
" set statusline=
set laststatus=2
set nu
