syntax on
set nobackup
set expandtab
set ai
set shiftwidth=4
set tabstop=4
set cursorline
set hlsearch
set incsearch
set showmode
set ruler
set showmatch
autocmd FileType make setlocal noexpandtab
autocmd FileType automake setlocal noexpandtab
